---
title: "List of Links to Repos"
author: "Lisa Schmid"
date: "October 27, 2015"
output: html_document
---

This document contains a list of links to repositories used in the class of this year's <a href="https://github.com/HertieDataScience/SyllabusAndLectures" target="_blank">MPP-E1180: Introduction to Collaborative Social Science Data Analysis</a> (CSSR) taught by <a href="https://github.com/christophergandrud
" target="_blank">@ChristopherGandrud</a> at the <a href="https://hertie-school.berlin" target="_blank">Hertie School of Governance</a>.

## Assignment 1
Please feel free to share the link to your repository from assignment 1 in the table below.

| Name of/Link to Contributor 1 | Name of/Link to Contributor 2 | Link to Repository |
|----|----|----|
| https://github.com/ChristopherCosler | https://github.com/LisaKatharina | https://github.com/ChristopherCosler/CSSR_Assignement1 |
|[Natalia](https://github.com/natalia-alvarado)|[Noriko](https://github.com/magaranoriko)|[our repo](https://github.com/magaranoriko/Assignment1/tree/master/session3) |
||||
| | | |
| | | |
| | | |

## Assignment 2

Please feel free to share the link to your repository for assignment 2 in the table below.

| Name of/Link to Contributor 1 | Name of/Link to Contributor 2 | Link to Repository |
|----|----|----|
| https://github.com/ChristopherCosler | https://github.com/LisaKatharina | https://github.com/ChristopherCosler/CSSR_ResearchProposal |
|[Claire](https://github.com/bctclc) |[Noriko](https://github.com/magaranoriko/) | [our repo](https://github.com/bctclc/Collaborative-Data-Analysis-Assignment2)|
|[Gabriel](https://github.com/gtarriba) |[Natalia](https://github.com/natalia-alvarado) |[2nd Assignment](https://github.com/natalia-alvarado/Second-Assignment)|
|[Lars] (https://github.com/LarsMehwald) |[Daniel] (https://github.com/dsalgadom) |[our repo](https://github.com/LarsMehwald/Assignment2) |
| | | |
| | | |
| | | |
| | | |
| | | |
| | | |
| | | |
| | | |
| | | |
| | | |
| | | |

## Assignment 3

Please feel free to share the link to your repository for assignment 3 in the table below.

| Name of/Link to Contributor 1 | Name of/Link to Contributor 2 | Link to Repository |
|----|----|----|
| https://github.com/ChristopherCosler | https://github.com/LisaKatharina | https://github.com/ChristopherCosler/CSSG_Dataanalysis |
| [Lars] (https://github.com/LarsMehwald) |[Daniel] (https://github.com/dsalgadom) | [our repo] (https://github.com/LarsMehwald/Assignment3)|
| | | |
| | | |
| | | |
| | | |
| | | |
| | | |
| | | |
| | | |
| | | |
| | | |
| | | |
| | | |
| | | |
